@baseUrl = http://localhost:5182
### CRUD

### Create User
POST {{baseUrl}}/user/create
Content-Type: application/json


{
    "username": "Felipe Smith",
    "email": "TacaramMassa@gmail.com",
    "password": "memes"
}

### To Check User
GET {{baseUrl}}/user/1

### Lista (caso houverem) todos os usuários presentes no banco
GET {{baseUrl}}/user/list

### Update User
PUT {{baseUrl}}/user/update/1
Content-Type: application/json


{
    "username": "Luiz Smith",
    "email": "CagueiNasCalça@gmail.com",
    "password": "rebolarPROScria"
}

### Delete User
DELETE {{baseUrl}}/user/delete/1

### C - CREATE
POST {{baseUrl}}/tasks/create
Content-Type: application/json


{
    "name": "acorda tarde",
    "description": "Preciso me preparar bem para a reunião depois da manhaa.",
    "userid": 1
}

### R - READ
GET {{baseUrl}}/tasks/list

### U - UPDATE
PUT {{baseUrl}}/tasks/update/1
Content-Type: application/json


{
    "name": "acorda",
    "description": "Preciso me preparar bem para a reunião depois da manhã.",
    "userid": 1
}

### D - DELETE 
DELETE  {{baseUrl}}/tasks/delete/1

### Create Label
PUT {{baseUrl}}/label/create
Content-Type: application/json

{
    "LabelName": "Estudar",
    "UserId": 1
}

### Delete Label
DELETE {{baseUrl}}/label/delete/1

### List Label
GET {{baseUrl}}/label/list/1