@baseUrl = http://localhost:5182
### CRUD

### Cria usuário
POST {{baseUrl}}/user/create
Content-Type: application/json

{
    "username": "Brian Santos",
    "email": "brian@gmail.com",
    "password": "testeusuario"
}

### Verificação do login
POST {{baseUrl}}/user/login
Content-Type: application/json

{
    "username": "Brian Santos",
    "email": "brian@gmail.com",
    "password": "testeusuario"
}

### Retorna as informações de um usuário específico
GET {{baseUrl}}/user/1

### Lista (caso houverem) todos os usuários presentes no banco
GET {{baseUrl}}/user/list

### Atualiza a(s) informação/informações de um usuário específico
PUT {{baseUrl}}/user/update/1
Content-Type: application/json

{
    "username": "Luiz Smith",
    "email": "luiz@email.com",
    "password": "testealteracao"
}

### Remove um usuário
DELETE {{baseUrl}}/user/delete/1

### Cria uma tarefa
POST {{baseUrl}}/tasks/create
Content-Type: application/json

{
    "name": "Acordar 8 horas",
    "description": "Preciso me preparar bem para a reunião das 10 horas.",
    "userid": 1
}

### Lista (caso houverem) todas as tarefas relacionadas a um usuário específico
GET {{baseUrl}}/tasks/list/Barone


### Atualiza as informações de uma tarefa em particular
PUT {{baseUrl}}/tasks/update/27
Content-Type: application/json

{
    "name": "Acordar 7 horas",
    "description": "Preciso me preparar bem para a reunião depois de amanhã.",
    "userid": 1
}

### Status Task
PATCH  {{baseUrl}}/tasks/status/25


### Remove uma tarefa em particular
DELETE  {{baseUrl}}/tasks/delete/1

### Cria uma/um etiqueta/rótulo (2)
POST {{baseUrl}}/label/create
Content-Type: application/json

{
    "LabelName": "ddsssdd",
    "UserId": 1
}

###
POST {{baseUrl}}/label/create

{
    "LabelName": "Estudar",
    "userid": 1
}

### Remove um rótulo em específico
DELETE {{baseUrl}}/label/delete/1

### Retorna todos os rótulos relacionados a um usuário em específico
GET {{baseUrl}}/label/list/Barone