@baseUrl = http://localhost:5182/api
### CRUD

### Create User
POST {{baseUrl}}/user/create
Content-Type: application/json


{
    "username": "Brian Santos",
    "email": "brian@gmail.com",
    "password": "testeusuario"
}

### To Check User
GET {{baseUrl}}/user/1

### Lista (caso houverem) todos os usuários presentes no banco
GET {{baseUrl}}/user/list

### Update User
PUT {{baseUrl}}/user/update/1
Content-Type: application/json


{
    "username": "Luiz Smith",
    "email": "luiz@email.com",
    "password": "testealteracao"
}

### Delete User
DELETE {{baseUrl}}/user/delete/1

### C - CREATE
POST {{baseUrl}}/tasks/create
Content-Type: application/json


{
    "name": "Acordar 8 horas",
    "description": "Preciso me preparar bem para a reunião das 10 horas.",
    "userid": 1
}

### Lista (caso houverem) todas aa tarefas relacionadas a um usuário
GET {{baseUrl}}/tasks/list/1

### U - UPDATE
PUT {{baseUrl}}/tasks/update/1
Content-Type: application/json


{
    "name": "Acordar 7 horas",
    "description": "Preciso me preparar bem para a reunião depois de amanhã.",
    "userid": 1
}

### D - DELETE 
DELETE  {{baseUrl}}/tasks/delete/1

### Create Label
PUT {{baseUrl}}/label/create
Content-Type: application/json

{
    "LabelName": "Estudar",
    "UserId": 1
}

### Delete Label
DELETE {{baseUrl}}/label/delete/1

### List Label
GET {{baseUrl}}/label/list/1